#!/bin/bash

echo "===== 📊 Perbandingan ELK Stack v7 vs v8 ====="
echo ""

echo "🔍 ELASTICSEARCH:"
echo "  v7.17.28:"
echo "    • Security: Optional (disabled by default)"
echo "    • Memory: 512MB default untuk WSL"
echo "    • Discovery: single-node"
echo "    • API: Legacy REST API"
echo ""
echo "  v8.15.0:"
echo "    • Security: Built-in tapi disabled untuk dev"
echo "    • Memory: 1GB (recommended untuk v8)"
echo "    • Discovery: single-node dengan modern config"
echo "    • API: Modern REST API dengan better error handling"
echo ""

echo "📊 KIBANA:"
echo "  v7.17.28:"
echo "    • UI: Classic Kibana interface"
echo "    • Saved Objects: Basic encryption"
echo "    • Performance: Good"
echo ""
echo "  v8.15.0:"
echo "    • UI: Modern, responsive interface"
echo "    • Saved Objects: Enhanced encryption"
echo "    • Performance: Improved rendering & caching"
echo "    • Features: Better lens, canvas, ML integration"
echo ""

echo "🔄 LOGSTASH:"
echo "  v7.17.28:"
echo "    • Memory: 512MB JVM heap"
echo "    • Pipeline: Basic configuration"
echo "    • Monitoring: Standard"
echo ""
echo "  v8.15.0:"
echo "    • Memory: 512MB JVM heap (same)"
echo "    • Pipeline: Enhanced with better error handling"
echo "    • Monitoring: Improved metrics & debugging"
echo "    • Performance: Better memory management"
echo ""

echo "📈 BEATS AGENTS:"
echo "  v7.17.28:"
echo "    • Filebeat: Basic log shipping"
echo "    • Metricbeat: System metrics"
echo "    • Heartbeat: Basic uptime monitoring"
echo "    • APM: Separate installation"
echo ""
echo "  v8.15.0:"
echo "    • Filebeat: Enhanced parsing & modules"
echo "    • Metricbeat: Extended metrics coverage"
echo "    • Heartbeat: Advanced synthetic monitoring"
echo "    • APM: Integrated dengan better tracing"
echo "    • Fleet: Centralized agent management"
echo ""

echo "🔐 SECURITY:"
echo "  v7.17.28:"
echo "    • Basic security (optional)"
echo "    • Manual SSL setup"
echo "    • Simple authentication"
echo ""
echo "  v8.15.0:"
echo "    • Security by default (disabled untuk dev)"
echo "    • Auto SSL certificate generation"
echo "    • Enhanced authentication & authorization"
echo "    • Better audit logging"
echo ""

echo "💡 REKOMENDASI PENGGUNAAN:"
echo ""
echo "📚 Gunakan v7.17.28 jika:"
echo "  • Tutorial/pembelajaran ELK basic"
echo "  • Resource terbatas (RAM < 4GB)"
echo "  • Kompatibilitas dengan sistem lama"
echo "  • Setup cepat tanpa security"
echo ""
echo "🚀 Gunakan v8.15.0 jika:"
echo "  • Production environment"
echo "  • Resource memadai (RAM >= 4GB)"
echo "  • Butuh security features"
echo "  • Ingin fitur terbaru (ML, Fleet, dll)"
echo "  • Long-term project"
echo ""

echo "⚙️  CARA MIGRASI v7 → v8:"
echo "  1. Backup semua data dan konfigurasi"
echo "  2. Uninstall ELK v7 (gunakan uninstall_elk_wsl.sh)"
echo "  3. Install ELK v8 (gunakan install_elk_v8_latest_wsl.sh)"
echo "  4. Migrate konfigurasi dan data"
echo "  5. Test semua functionality"
echo ""

echo "📊 PERFORMA COMPARISON (WSL Ubuntu):"
echo "┌─────────────────┬──────────────┬──────────────┐"
echo "│ Component       │ v7.17.28     │ v8.15.0      │"
echo "├─────────────────┼──────────────┼──────────────┤"
echo "│ Elasticsearch   │ ~800MB RAM   │ ~1.2GB RAM   │"
echo "│ Kibana          │ ~200MB RAM   │ ~300MB RAM   │"
echo "│ Logstash        │ ~300MB RAM   │ ~350MB RAM   │"
echo "│ Total RAM       │ ~1.3GB       │ ~1.85GB      │"
echo "│ Startup time    │ ~90 seconds  │ ~120 seconds │"
echo "└─────────────────┴──────────────┴──────────────┘"
echo ""

echo "🎯 KESIMPULAN:"
echo "  • v7: Lebih ringan, cocok untuk learning & development"
echo "  • v8: Lebih powerful, cocok untuk production & advanced features"
echo "  • Keduanya stabil dan supported oleh Elastic"
echo ""
